In [1]:
import pandas as pd
import openpyxl

In [2]:
raw_df = pd.read_excel("dataset_breast/BrEaST-Lesions-USG-clinical-data-Dec-15-2023.xlsx")

In [5]:
raw_df["Interpretation"].str.split("&", expand=True)

,0,1,2,3,4,5
0,Breast scar (surgery),Breast scar (radiotherapy),NaN,NaN,NaN,NaN
1,Dysplasia,Fibroadenoma,NaN,NaN,NaN,NaN
2,Duct filled with thick fluid,Intraductal papilloma,NaN,NaN,NaN,NaN
3,Cyst filled with thick fluid,NaN,NaN,NaN,NaN,NaN
4,Suspicion of malignancy,Intraductal papilloma,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
251,Fibroadenoma,NaN,NaN,NaN,NaN,NaN
252,Fat necrosis,Breast scar (surgery),NaN,NaN,NaN,NaN
253,Suspicion of malignancy,NaN,NaN,NaN,NaN,NaN
254,Suspicion of malignancy,Mastitis,NaN,NaN,NaN,NaN
255,Fibroadenoma,NaN,NaN,NaN,NaN,NaN

In [6]:
raw_df["Interpretation"].str.split("&", expand=True).describe()

,0,1,2,3,4,5
count,256,149,86,29,6,1
unique,18,19,12,6,5,1
top,Suspicion of malignancy,Fibroadenoma,Intraductal papilloma,Intraductal papilloma,Intraductal papilloma,Intraductal papilloma
freq,149,49,36,18,2,1

In [19]:
uniques_count = {}
for val in raw_df["Interpretation"]:
    for item in val.split("&"):
        item = item.strip()
        if item in uniques_count:
            uniques_count[item] += 1
        else:
            uniques_count[item] = 1

for unique, count in uniques_count.items():
    print(f"{unique}: {count}")

Breast scar (surgery): 6
Breast scar (radiotherapy): 1
Dysplasia: 66
Fibroadenoma: 101
Duct filled with thick fluid: 12
Intraductal papilloma: 68
Cyst filled with thick fluid: 31
Suspicion of malignancy: 149
Mastitis: 6
Complex cyst / Non-simple cyst: 27
Mammary duct ectasia: 13
Hamartoma: 8
Isolated calcifications: 1
Silicone implant: 4
Adenosis: 2
not applicable: 4
Simple cyst: 4
Intramammary lymph node: 4
Hematoma: 4
Phyllodes tumor: 2
Lipoma: 4
Abscess: 1
Hemangioma: 1
Implant rupture: 2
Lacteal cyst: 2
Seroma: 1
Fat necrosis: 2
Lactating adenoma: 1

In [13]:
uniques_count = {}
for val in raw_df["Signs"]:
    for item in val.split("&"):
        item = item.strip()
        if item in uniques_count:
            uniques_count[item] += 1
        else:
            uniques_count[item] = 1

for unique, count in uniques_count.items():
    print(f"{unique}: {count}")

breast scar: 5
not available: 46
no: 147
nipple retraction: 3
palpable: 58
skin retraction: 4
peau d`orange: 1
warmth: 4
redness: 3

In [16]:
uniques_count = {}
for val in raw_df["Margin"]:
    val = val.split(" - ")[1] if " - " in val else val
    for item in val.split("&"):
        item = item.strip()
        if item in uniques_count:
            uniques_count[item] += 1
        else:
            uniques_count[item] = 1

for unique, count in uniques_count.items():
    print(f"{unique}: {count}")

indistinct: 115
circumscribed: 115
spiculated: 33
angular: 42
microlobulated: 36
not applicable: 4

In [18]:
uniques_count = {}
for val in raw_df["Symptoms"]:
    for item in val.split("&"):
        item = item.strip()
        if item in uniques_count:
            uniques_count[item] += 1
        else:
            uniques_count[item] = 1

for unique, count in uniques_count.items():
    print(f"{unique}: {count}")

family history of breast/ovarian cancer: 22
not available: 98
nipple discharge: 7
no: 113
HRT/hormonal contraception: 17
personal history of breast cancer: 3
breast injury: 1

In [30]:
uniques_count = {}
for val in raw_df["Tissue_composition"]:
    for item in val.split("&"):
        item = item.strip()
        if item in uniques_count:
            uniques_count[item] += 1
        else:
            uniques_count[item] = 1

for unique, count in uniques_count.items():
    print(f"{unique}: {count}")

heterogeneous: predominantly fat: 80
homogeneous: fat: 24
homogeneous: fibroglandular: 46
heterogeneous: predominantly fibroglandular: 56
not available: 49
lactating: 7

In [40]:
uniques_count = {}
for val in raw_df["Diagnosis"]:
    for item in val.split("&"):
        item = item.strip()
        if item in uniques_count:
            uniques_count[item] += 1
        else:
            uniques_count[item] = 1

for unique, count in uniques_count.items():
    print(f"{unique}: {count}")

not applicable: 59
Intramammary lymph node: 1
Usual ductal hyperplasia (UDH): 7
Pseudoangiomatous stromal hyperplasia (PASH): 6
Encapsulated papillary carcinoma: 2
Ductal carcinoma in situ (DCIS): 14
Fibrosclerosis: 11
Invasive carcinoma of no special type (NST): 66
Invasive micropapillary carcinoma: 4
Benign mammary dysplasia: 27
Fibroadenoma: 30
Intraductal papilloma: 8
Tubular carcinoma: 2
Cribriform carcinoma: 3
Lactating adenoma: 1
Invasive lobular carcinoma: 13
Complex sclerosing lesion: 1
Lobular carcinoma in situ (LCIS): 2
Phyllodes tumor: 3
Hamartoma: 1
Fibrocystic change: 2
Mucinous carcinoma: 4
Fat necrosis: 1
Lymphoma: 1
Adenosis: 1
Simple cyst: 1
Mastitis: 2
Sebaceous carcinoma: 1
Metaplastic carcinoma: 1
Atypical lobular hyperplasia (ALH): 1
Apocrine carcinoma: 1
Solid papillary carcinoma in situ: 1
Fibroadenosis: 1
Invasive papillary carcinoma: 1

In [41]:
inter_dummies = raw_df["Interpretation"].str.get_dummies(sep="&")
marg_dummies = raw_df["Margin"].apply(lambda x: x.split(" - ")[1] if " - " in x else x).str.get_dummies(sep="&")
sigs_dummies = raw_df["Signs"].str.get_dummies(sep="&")
symp_dummies = raw_df["Symptoms"].str.get_dummies(sep="&")
tis_dummies = raw_df["Tissue_composition"].str.get_dummies(sep="&")
diag_dummies = raw_df["Diagnosis"].str.get_dummies(sep="&")

In [21]:
inter_dummies

,Abscess,Adenosis,Breast scar (radiotherapy),Breast scar (surgery),Complex cyst / Non-simple cyst,Cyst filled with thick fluid,Duct filled with thick fluid,Dysplasia,Fat necrosis,Fibroadenoma,...,Lacteal cyst,Lipoma,Mammary duct ectasia,Mastitis,Phyllodes tumor,Seroma,Silicone implant,Simple cyst,Suspicion of malignancy,not applicable
0,0,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
252,0,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
253,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
254,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
255,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
useful_raw_features = ["Age", "Shape", "Echogenicity", "Posterior_features", "Halo", "Calcifications", "Skin_thickening", "BIRADS", "Verification", "Classification"]

In [27]:
raw_df[useful_raw_features].describe(include="all")

,Age,Tissue_composition,Shape,Echogenicity,Posterior_features,Halo,Calcifications,Skin_thickening,BIRADS,Verification,Diagnosis,Classification
count,256,256,256,256,256,256,256,256,256,256,256,256
unique,62,9,4,7,5,3,5,2,7,3,45,3
top,not available,heterogeneous: predominantly fat,irregular,hypoechoic,no,no,no,no,4c,confirmed by biopsy,not applicable,benign
freq,42,79,140,148,159,197,225,241,49,197,59,154

In [28]:
raw_df[useful_raw_features].head()

,Age,Tissue_composition,Shape,Echogenicity,Posterior_features,Halo,Calcifications,Skin_thickening,BIRADS,Verification,Diagnosis,Classification
0,57,heterogeneous: predominantly fat,irregular,heterogeneous,shadowing,no,no,yes,2,confirmed by follow-up care,not applicable,benign
1,not available,homogeneous: fat,oval,hypoechoic,no,no,no,no,4b,confirmed by biopsy,Intramammary lymph node,benign
2,56,heterogeneous: predominantly fat,oval,hyperechoic,no,no,no,no,4a,confirmed by biopsy,Usual ductal hyperplasia (UDH)&Pseudoangiomato...,benign
3,43,homogeneous: fibroglandular,round,hypoechoic,no,no,no,no,3,confirmed by follow-up care,not applicable,benign
4,67,homogeneous: fat,oval,complex cystic/solid,enhancement,no,no,no,4b,confirmed by biopsy,Encapsulated papillary carcinoma&Ductal carcin...,malignant

In [32]:
raw_df["Shape"].value_counts()

Shape
irregular         140
oval               97
round              15
not applicable      4
Name: count, dtype: int64

In [33]:
raw_df["Echogenicity"].value_counts()

Echogenicity
hypoechoic              148
heterogeneous            57
anechoic                 15
isoechoic                12
complex cystic/solid     11
hyperechoic               9
not applicable            4
Name: count, dtype: int64

In [34]:
raw_df["Posterior_features"].value_counts()

Posterior_features
no                159
shadowing          50
enhancement        36
combined            7
not applicable      4
Name: count, dtype: int64

In [35]:
raw_df["Halo"].value_counts()

Halo
no                197
yes                55
not applicable      4
Name: count, dtype: int64

In [36]:
raw_df["Calcifications"].value_counts()

Calcifications
no                225
in a mass          23
not applicable      4
intraductal         2
indefinable         2
Name: count, dtype: int64

In [37]:
raw_df["Skin_thickening"].value_counts()

Skin_thickening
no     241
yes     15
Name: count, dtype: int64

In [38]:
raw_df["Verification"].value_counts()

Verification
confirmed by biopsy            197
confirmed by follow-up care     55
not applicable                   4
Name: count, dtype: int64

In [42]:
raw_df["Classification"].value_counts()

Classification
benign       154
malignant     98
normal         4
Name: count, dtype: int64